# This file intentionally left blank

BOARD = GENERIC_RP_RP2040

#Console Debug
CONSOLE_ENABLE = yes
DEBUG_ENABLE = yes

#OLED
OLED_ENABLE = no
OLED_DRIVER = SSD1306

#Joystick
ANALOG_ENABLE = yes
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog

#POINTING DEVICE
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick

ANALOG_JOYSTICK_X_AXIS_PIN = GP27
ANALOG_JOYSTICK_Y_AXIS_PIN = GP28
#ANALOG_JOYSTICK_AXIS_MIN = 0
#ANALOG_JOYSTICK_AXIS_MAX = 1023
#ANALOG_JOYSTICK_SPEED_REGULATOR = 20
#ANALOG_JOYSTICK_READ_INTERVAL = 10
#ANALOG_JOYSTICK_SPEED_MAX = 2
#ANALOG_JOYSTICK_CLICK_PIN



#RGB
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
WS2812_DRIVER = vendor

OPT_DEFS += -DHAL_USE_I2C=TRUE


# Project specific files
SRC += oled_handler.c

SRC += analog.c




